### ISSUE TITLE
 AgentBethRewards.handleBlock: unexpected block hash

### ISSUE THREAD

**Issue by arwer13** [lidofinance/alerting-forta#10]
Error in AgentBethRewards.handleBlock
Error: unexpected block hash
https://explorer.forta.network/alert/0xfbc3b530460058934d656db2066f1dc9f7bc8b93538c669654626a78cc087351

The error occurred ~ Jan 23 for the first time on single scan node.

It seems there is a problem in synchronisation of agent-beth-rewards and agent-lido-oracle.

**Comment by dgusakov** [comment]
All agents are now independent. The source of the issue is eliminated.
