### ISSUE TITLE
Cannot read property 'periodFinish' of undefined

### ISSUE THREAD

**Issue by arwer13** [lidofinance/alerting-forta#11]
Error in AgentPoolsRewards.handleBlock
TypeError: Cannot read property 'periodFinish' of undefined

https://explorer.forta.network/alert/0x85fbc5f6b3e9842c89fa1d3d92572009a66cc9d7d8cfe53c37eefc1ace22e897

**Comment by dgusakov** [comment]
Closing as no longer relevant
