### ISSUE TITLE
Add more networks for `l2-bridge-ethereum`

### ISSUE THREAD

**Issue by TheDZhon** [lidofinance/alerting-forta#433]
Currently, the `l2-bridge-ethereum` agent supports only:
- wstETH on Arbitrum bridge (L1 part)
- wstETH on Arbitrum bridge (L2 part)

Worth extending support for:
- wstETH on Base (L1 part, as the network in production atm)
- wstETH on zkSync (L1 part, as the network in the proposed state)

@sergeyWh1te, it would be great if you could take over the initiative here
cc: @arwer13 for future improvement (we missed this part for Base I guess)

**Comment by sergeyWh1te** [comment]
https://github.com/lidofinance/alerting-forta/pull/434
